feat(#44): add register page
Boyadjie/UnVoy pull request #51
Opened 2024-04-08 17:22 UTC by sologames7

## ✅ How to validate this PR?

Run preview and review files changed

2024-04-14 09:38 UTC, Boyadjie requested changes

2024-04-14 09:38 UTC, Boyadjie commented on .gitignore
> +firebase.js
Pquestion: pourquoi on enleve ce fichier ?

2024-04-14 09:38 UTC, Boyadjie commented on app/register/page.tsx
> +'use client';
Suggestion : au vu de la page on doit pouvoir ce passer du use client

2024-04-14 09:38 UTC, Boyadjie commented on public/illustrations/auth/orangeBase.svg
Probleme : on ne devrais pas avoir a séparer un svg en plusieurs morceaux, tu peux l'import sans le mettre en image pour l'intégrer et animer dessus dirrectement, par contre il faut que le svg sois bien fait avec des id pour cibler les bons éléments

2024-04-14 09:38 UTC, Boyadjie commented on public/illustrations/auth/owl.svg
Suggestion: rename en logo  ?

2024-04-14 09:38 UTC, Boyadjie commented on src/components/authentication/ConnectionWith.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unused-vars
Problème: Une erreur ts ne se fixe pas avec un ignore, c'est vraiment pas une bonne pratique.
Question: si la variable n'est pas utilisée pourquoi la garder ?

2024-04-14 09:38 UTC, Boyadjie commented on src/components/authentication/ForgotPassword.tsx
> +};
Nitpicking: sur des petits types comme ça, c'est pas necessaire de créer un objet a part, voir même ça complexifie la lecture

2024-04-14 09:38 UTC, Boyadjie commented on src/components/authentication/ForgotPassword.tsx
> +    // move logic to back end file useing next.js api routes
??

2024-04-14 09:38 UTC, Boyadjie commented on src/components/authentication/ForgotPassword.tsx
> +        {/* use image from next */}
🗑️

2024-04-14 09:38 UTC, Boyadjie commented on src/components/authentication/Inputs/InputManager.tsx
Question: du coup on utilise ce composant la ?

2024-04-14 09:38 UTC, Boyadjie commented on src/components/authentication/LoginForm.tsx
> +    // move logic to back end file useing next.js api routes
🗑️

2024-04-14 09:38 UTC, Boyadjie commented on src/components/authentication/LoginForm.tsx
> +        {/* use image from next */}
🗑️

2024-04-14 09:38 UTC, Boyadjie commented on src/components/authentication/RegisterForm.tsx
> +  const isValidPassword = formValues.password.length >= 8;
Suggestion: ça vaudrait le coup de faire une fonction utilitaire qui fait la validation, t'en pense quoi ?
Elle pourrait prendre en parametre un objet de type form (avec les inputs et les bons types associé) et retourner true ou un tableau d'erreur ? ou un objet errur que tu destructure pour afficher specifiquement jsp

2024-04-14 09:38 UTC, Boyadjie commented on src/components/authentication/RegisterForm.tsx
> +    // move logic to back end file useing next.js api routes
🗑️

2024-04-14 09:38 UTC, Boyadjie commented on src/components/authentication/RegisterForm.tsx
> +        // eslint-disable-next-line no-console
🗑️

2024-04-14 09:38 UTC, Boyadjie commented on src/components/authentication/TextAndRoute.tsx
> +interface TextAndRouteProps {
Nitpick: Type

2024-04-14 09:38 UTC, Boyadjie commented on src/components/authentication/TextAndRoute.tsx
Question: il sert a quoi ce composant ?

2024-04-14 09:38 UTC, Boyadjie commented on src/components/authentication/Title.tsx
> +  };
Question: Pourquoi faire appel au router alors que tu peux utiliser un Link next.js ?

2024-04-14 09:38 UTC, Boyadjie commented on src/components/landing/header/BurgerNav.tsx
>    const onClickHandler = async (e: any) => {
Probleme: le any ne devrait pas etre la, et donc le commentaire non plus, e c'est un mouseEvent surement

2024-04-14 09:38 UTC, Boyadjie commented on src/components/landing/team/Member.tsx
> +  const [, setVw] = useState(0);
Question: un state dont on utilise pas la valeur est vraiment utile ?

2024-04-14 09:38 UTC, Boyadjie commented on src/context/AuthContext.tsx
> +type SetStateAction<S> = S | ((prevState: S) => S);
Nitpick: c'est pas tres compréhensible les A et S

2024-04-14 09:38 UTC, Boyadjie commented on src/firebase.js
Il y a beaucoup de comm ici...

2024-04-14 15:53 UTC, sologames7 commented on .gitignore
> +firebase.js
je pensais cacher les clés mais oklm en fait le repo est sensé etre privé

2024-05-27 16:45 UTC, sologames7 commented on public/illustrations/auth/orangeBase.svg
jvais skip pour prioriser

2024-05-27 16:54 UTC, sologames7 commented on src/components/authentication/ForgotPassword.tsx
> +};
ok

2024-05-27 16:55 UTC, sologames7 commented on src/components/authentication/ForgotPassword.tsx
> +        {/* use image from next */}
ok

2024-05-27 16:55 UTC, sologames7 commented on src/components/authentication/LoginForm.tsx
> +    // move logic to back end file useing next.js api routes
ok

2024-05-27 16:56 UTC, sologames7 commented on src/components/authentication/Inputs/InputManager.tsx
j'avoue j'ai dupliqué le dossier pour refaire un form j'ai pas trop réfléchi mais pour les prochains pas besoin.

2024-05-27 17:30 UTC, sologames7 commented on src/components/authentication/TextAndRoute.tsx
pour les sections du style 'mot de passe oublié ? cliquez ICI (lien)', deja un compte ? ici (lien)

2024-05-27 18:26 UTC, Boyadjie approved these changes

2024-05-28 15:54 UTC, merged